name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install black
        run: |
          python -m pip install black
      - name: Check code formatting with black
        run: |
          black --check --diff .

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pylint
        run: |
          python -m pip install pylint
          python -m pip install -r requirements.txt
      - name: Run Pylint
        run: |
          pylint --ignore-paths=.venv .

  release: # Release job only if lint job succeeds
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install necessary packages
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller --onefile skillsync.py
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: "v${GITHUB_REF_NAME}"
        run: |
          gh release create "${RELEASE_NAME}" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${RELEASE_NAME}" \
            --generate-notes
          # Upload asset
          gh release upload "${RELEASE_NAME}" --repo="$GITHUB_REPOSITORY" --clobber dist/skillsync/skillsync
